# Generated by Django 4.2.1 on 2023-06-08 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages={'required': 'Custom error message'}, max_length=50, verbose_name='First - Name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5, message='Custom message')])),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
