# Generated by Django 4.2.1 on 2023-05-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_person_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(error_messages={'required': 'Custom error message'}, max_length=50, verbose_name='First - Name'),
        ),
    ]
